# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gatxSpawKg5gAgog46XJd81arZSu1_fT
"""

import pandas as pd

"""# Reading File"""

df = pd.read_csv("/content/server_logs.csv")
df

"""## Fixing Datatypes"""

df['timestamp'] = pd.to_datetime(df['timestamp'])
df[['response_time_ms', 'dest_port']] = df[['response_time_ms', 'dest_port']].apply(pd.to_numeric)
df[['response_code', 'event_id', 'source_ip', 'event_type', 'user_agent', 'endpoint', 'http_method', 'query_params', 'username', 'auth_result', 'failure_reason', 'protocol', 'connection_result']] = df[['response_code', 'event_id', 'source_ip', 'event_type', 'user_agent', 'endpoint', 'http_method', 'query_params', 'username', 'auth_result', 'failure_reason', 'protocol', 'connection_result']].astype(object)

"""# Adding new columns"""

import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

df["has_query_params"] = df["query_params"].notna()

df["num_params"] = df["query_params"].apply(lambda x: len(str(x).split("&")) if pd.notna(x) else 0)
df["avg_param_length"] = df["query_params"].apply(
    lambda x: sum(len(p) for p in str(x).split("&"))/len(str(x).split("&")) if pd.notna(x) else 0
)

df["has_sql_keywords"] = df["query_params"].apply(
    lambda x: bool(re.search(r"(select|union|drop|--)", str(x).lower())) if pd.notna(x) else False
)
df["has_html_tags"] = df["query_params"].apply(
    lambda x: bool(re.search(r"<.*?>", str(x).lower())) if pd.notna(x) else False
)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["query_params"].fillna(""))

df["has_username"] = df["username"].notna()
df["has_source_ip"] = df["source_ip"].notna()
df["has_dest_port"] = df["dest_port"].notna()

def categorize_port(port):
    if pd.isna(port): return "none"
    port = int(port)
    if port < 1024: return "well_known"
    elif port < 49152: return "registered"
    else: return "ephemeral"

df["port_category"] = df["dest_port"].apply(categorize_port)

high_risk = {21,22,23,25,80,443,3389}
df["is_high_risk_port"] = df["dest_port"].apply(lambda x: int(x) in high_risk if pd.notna(x) else False)

"""## Temporal Feature Engineering"""

df = df.sort_values(["source_ip", "timestamp"])

df["time_since_last_event"] = df.groupby("source_ip")["timestamp"].diff().dt.total_seconds()

df["avg_gap"] = df.groupby("source_ip")["time_since_last_event"].transform(
    lambda x: x.rolling(5, min_periods=1).mean()
)

df["session_id"] = (df.groupby("source_ip")["timestamp"]
                      .diff().dt.total_seconds().gt(1800)
                      .cumsum())

df["events_per_session"] = df.groupby(["source_ip","session_id"])["event_id"].transform("count")

df["session_length"] = df.groupby(["source_ip","session_id"])["timestamp"].transform(lambda x: (x.max()-x.min()).total_seconds())

"""# Filling nan"""

df[df.select_dtypes('object').columns] = df.select_dtypes('object').fillna("None")
df[df.select_dtypes('number').columns] = df.select_dtypes('number').fillna(0)

"""# Drop Unnecessary Columns"""

df = df.drop(columns=['timestamp', 'source_ip', 'query_params', 'dest_port', 'username'], axis=1)

"""# Transform Columns

## Numerical Transformation
"""

from sklearn.preprocessing import StandardScaler

num_cols = df.select_dtypes(include='number').columns

scaler = StandardScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

"""## Categorical Transformation"""

df = pd.get_dummies(df, columns=df.drop('event_id', axis=1).select_dtypes(include="object").columns)

df

X

"""# Modeling"""

import json

keys = []
values = []

with open("/content/ground_truth.json") as file:
  content = file.read()
  content = json.loads(content)
  keys = list(content.keys())
  values = list(content.values())

y = pd.DataFrame({'event_id': keys, 'defect': values})
df = df.merge(y, on='event_id', how='left')

from sklearn.preprocessing import LabelEncoder

df['defect'] = df['defect'].fillna('No_Defect')

mapping = {
    'No_Defect': 0,
    'DOS': 1,
    'PORT_SCAN': 2,
    'BRUTE_FORCE': 3,
    'SQL_INJECTION': 4,
    'XSS': 5,
    'UNAUTHORIZED_ACCESS': 6,
    'COMMAND_INJECTION': 7,
    'PATH_TRAVERSAL': 8
}

df['defect'] = df['defect'].map(mapping)

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.metrics import accuracy_score, classification_report

# x = df.drop(['event_id', 'defect'], axis=1)
# y = df['defect']
X_df = pd.DataFrame.sparse.from_spmatrix(X, columns=vectorizer.get_feature_names_out())

x = pd.concat([x, X_df], axis=1)

outlier_fraction = len(df[df['defect'] != 0])/len(df)

model =  IsolationForest(n_estimators=100, contamination=outlier_fraction, random_state=42)
model.fit(x)

y_test = y
y_test.loc[y_test!=0] = 1
scores_prediction = model.decision_function(x)
y_pred = model.predict(x)
y_pred[y_pred == 1] = 0
y_pred[y_pred == -1] = 1
print("Accuracy in finding anomaly:",accuracy_score(y_test,y_pred))

print("Accuracy in finding anomaly:",accuracy_score(y_test,y_pred))